version: 0.2
env:
  variables:
    ECR_REPO: 727646491714.dkr.ecr.us-east-1.amazonaws.com/lks-catalog-image
    ECR_REGION: us-east-1
    CONTAINER_NAME: lks-catalog-container

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Install Dependencies and login into ECR"
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPO || exit 1
  build:
    commands:
      - echo "Run unit testing and build docker image"
      - docker build -t $CONTAINER_NAME:latest . || exit 1
  post_build:  # Sudah berada di dalam phases dengan indentasi yang benar
    commands:
      - echo "Pushing the image to ECR..."
      - docker tag $CONTAINER_NAME:latest $ECR_REPO:latest
      - docker tag $CONTAINER_NAME:latest $ECR_REPO:${CODEBUILD_BUILD_NUMBER}
      
      - echo "Pushing the latest image..."
      - docker push $ECR_REPO:latest || exit 1
      
      - echo "Pushing the build number image..."
      - docker push $ECR_REPO:${CODEBUILD_BUILD_NUMBER} || exit 1
      
      # Perubahan di sini untuk memastikan 'imagedefinitions.json' hanya berisi 'latest'
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_REPO:latest > imagedefinitions.json
      
      - if [ -f imagedefinitions.json ]; then
          echo "imagedefinitions.json file created successfully.";
        else
          echo "Failed to create imagedefinitions.json file.";
          exit 1;
        fi

artifacts:
  files:
    - imagedefinitions.json
